spring:
  application:
    name: custom-tomcat-datasource
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      data-locations: classpath:sql/CreateSchema.sql, classpath:sql/InsertSchema.sql
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings.trace: true
      settings.web-allow-others: false
server:
  servlet:
    context-path: "/customtomcatdatasource"
  port: 8080

h2.database:
  jdbcUrl: jdbc:h2:mem:EmployeeDB
  driverClassName: org.h2.Driver
  username: sa
  password: password
  maxActive: 20
  maxIdle: 5


