INSERT  INTO EMPLOYEE (ID, NAME, LOCATION) VALUES (1, 'Sam', 'NewYork');
INSERT  INTO EMPLOYEE (ID, NAME, LOCATION) VALUES (2, 'Trent', 'Boston');
INSERT  INTO EMPLOYEE (ID, NAME, LOCATION) VALUES (3, 'Vijay', 'Bentonville');
INSERT  INTO EMPLOYEE (ID, NAME, LOCATION) VALUES (4, 'Sandeep', 'Hartford');
INSERT  INTO EMPLOYEE (ID, NAME, LOCATION) VALUES (5, 'Sekhar', 'NewJersey');